= NotesMongoDB
:Author: Gabriele Puliti
:Email: gabriele.puliti@gmail.com
:Date: 26/06/2019
:Revision: 0.1.0

== Introduction

MongoDB enforces no schemas, so Documents don't have to use the same schema inside of one collection.

*But* it recommended to Use some sort of schemas to prevent missusing of the Documents.

== Install

TIP: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/#install-mongodb-community-edition-using-deb-packages[Install Mongo on Ubuntu]

TIP: https://www.mongodb.com/download-center/community[MongoDB server community edition]

To test if the database are installed you can check by running:

[source,bash]
----
mongod --version
----

== Start database

By default uses /data/db as the storage path, if follow this standard
you can start database without any arguments. Run this on terminal:

[source,bash]
----
mongod --dbpath "my/new/path"
----

or

[source,bash]
----
mongod
----

WARNING: to run the mongodb server it's necessary the sudoers permissions

== Use mongo

From another terminal run:

[source,mongo]
----
mongo --port <port_where_database_are>
----

Example:

[source,bash]
----
mongo --port 27018
----

== Database infos

[source,mongo]
----
show dbs
----

== Create new database

A Database holds multiple Collections where each Collection can then hold multiple Documents.

[source,mongo]
----
use <name_of_new_database>
----

example:

[source,mongo]
----
use shop
----

== Reset/Delete Database

To get rid of the datas:

* load the database get rid of:
+
[source,mongo]
----
use databaseName
----
* execute:
+
[source,mongo]
----
db.dropDatabase()
----

== CRUD operations

MongoDB offers multiples CRUD operations for single-document and bulk actions.
Some methods require an argument and others don't.

* Create:
+
[source,mongo]
----
insertOne(data, options)
----
+
[source,mongo]
----
insertMany(data, options)
----
* Read:
+
[source,mongo]
----
find(filter, options)
----
+
[source,mongo]
----
findOne(filter, options)
----
* Update:
+
[source,mongo]
----
updateOne(filter, data, options)
----
+
[source,mongo]
----
updateMany(filter, data, options)
----
+
[source,mongo]
----
replaceOne(filter, data, options)
----
* Delete:
+
[source,mongo]
----
deleteOne(filter, options)
----
+
[source,mongo]
----
deleteMany(filter, options)
----

== Insert data to database

A Document can't directly be insered into a Database, you need to use a Colleciton.
Each document needs a unique ID, if is not given the engine of mongo will create it for us.
It's possible to have embedded docuemnts and array fields.

[source,mongo]
----
db.<name_of_collection>.insertOne({"key0":value0, key1:value1})
----

The values type can be:

* *String*
* *Number*
* *Boolean*
* *Object*
* *Array*

example:

[source,mongo]
----
db.products.insertOne({
    name: "computer",
    price: 100.999,
    description: "This is a high value product.",
    details:{
        cpu: "Intel i7",
        "memory": "32",
		stored: true
    }
})
----

== Insert many datas to database

[source,mongo]
----
db.<name_of_collection>.insertMany([
    {
        "key0":"value0",
        key1:"value1"
    },
    {
        "key2":"value2",
        key3:"value3"
    }
])
----

example:

[source,mongo]
----
db.flightData.insertMany([
    {
        "departureAirport": "MUC",
        "arrivalAirport": "SFO",
        "aircraft": "Airbus A380",
        "distance": 12000,
        "intercontinental": true
    },
    {
        "departureAirport": "LHR",
        "arrivalAirport": "TXL",
        "aircraft": "Airbus A320",
        "distance": 950,
        "intercontinental": false
    }
])
----

== Retrive data from database

=== Find

CAUTION: The find method return a cursor and not a list of documents, because the documents retrive can be thousand and it's more easy to transfert over the net. It can be also possible to use filters to limit the number of documents retrive, or projection to limit the set of fields.

[source,mongo]
----
db.<name_of_collection>.find(filters, options)
----

To beautify the results it can be use the pretty function:

[source,mongo]
----
db.<name_of_collection>.find(filter, options).pretty()
----

example:

[source,mongo]
----
db.products.find().pretty()
----

[source,mongo]
----
db.<name_of_collection>.find({intercontinental: true}).pretty()
----

[source,mongo]
----
db.flightData.find({distance:{$gt:100}}).pretty()
----

[source,mongo]
----
db.passengers.find().toArray()
----

[source,mongo]
----
db.passengers.find().forEach((passengerData) => {printjson(passengerData)})
----

The use of find below is called projection:

[source,mongo]
----
db.passengers.find({}, {name:1}).pretty()
----

=== FindOne

[source,mongo]
----
db.<name_of_collection>.findOne()
----

example:

[source,mongo]
----
db.flightData.findOne({distance:{$gt:100}})
----

== Accessing structured datas

=== E.G. 1

[source,mongo]
----
db.passengers.findOne({name: "Albert Twostone"}).hobbies
----

Output:

[source,mongo]
----
["sports", "cooking"]
----

=== E.G. 2

[source,mongo]
----
db.flightData.find({"status.details.responsible": "Max Schwarzmuller"}).pretty()
----

Output:

[source,json]
----
{
    "_id" : ObjectId("5d09ef2276acd23a2e3fb02b"),
    "departureAirport" : "MUC",
    "arrivalAirport" : "SFO",
    "aircraft" : "Airbus A380",
    "distance" : 12000,
    "intercontinental" : true,
    "status" : {
        "description" : "on-time",
        "lastUpdated" : "1 hour ago",
        "details" : {
            "responsible" : "Max Schwarzmuller"
        }
    }
}
{
    "_id" : ObjectId("5d09ef2276acd23a2e3fb02c"),
    "departureAirport" : "LHR",
    "arrivalAirport" : "TXL",
    "aircraft" : "Airbus A320",
    "distance" : 950,
    "intercontinental" : false,
    "status" : {
        "description" : "on-time",
        "lastUpdated" : "1 hour ago",
        "details" : {
            "responsible" : "Max Schwarzmuller"
        }
    }
}
----

== Delete data from database

[source,mongo]
----
db.<name_of_collection>.deleteOne({key_filter: value_filter})
----

example:

[source,mongo]
----
db.fightData.deleteOne({departureAirport: "1"})
----

[source,mongo]
----
db.fightData.deleteMany({marker: "toDelete"})
----

[source,mongo]
----
db.fightData.deleteMany({})
----

== Drop collection

[source,mongo]
----
db.<name_of_collection>.drop()
----

== Update data

Be worry about the update function, the first one replace all the
filtered data:

[source,mongo]
----
db.<name_of_collection>.update(
    {key_filter: value_filter},
    {key_update: value_update}
)
----

This second type of update need a option:

[source,mongo]
----
db.<name_of_collection>.updateOne(
    {key_filter: value_filter},
    {$option: {key_update: value_update}}
)
----

example:

[source,mongo]
----
db.flightData.updateOne(
    {departureAirport:"123"},
    {$set:{marker: 'delete'}}
)
----

[source,mongo]
----
db.flightData.updateMany(
    {},
    {$set: {
        marker: 'toDelete'
    }}
)
----

[source,mongo]
----
db.flightData.update(
    {"_id":ObjectId("5d09ef2276acd23a2e3fb02b")},
    {delayed:false}
)
----

== Replace Data

[source,mongo]
----
db.<name_of_collection>.replaceOne(filter, options)
----

example:

[source,mongo]
----
db.flightData.replaceOne(
    {"_id": ObjectId("5d09ef2276acd23a2e3fb02b")},
    {
        "departureAirport": "MUC",
        "arrivalAirport": "SFO",
        "aircraft": "Airbus A380",
        "distance": 12000,
        "intercontinental": true
    }
)
----

== Nested documents

[source,mongo]
----
db.flightData.updateMany(
    {},
    {$set: {
        status: {
            description: "on-time",
            lastUpdated: "1 hour ago",
            details: {
                responsible: "Max Schwarzmuller"
            }
        }
    }}
)
----

== Embedded documents and max document value

In MongoDB it’s possible to have at least 100 levels of nesting.
Documents have a maximum size of 16MB.

== Mongo drivers

https://docs.mongodb.com/ecosystem/drivers/

== Exercises

=== Exercise 0

.Introduction
Create a database of patients, every patient need to have this arguments:

* firstName
* lastName
* age
* history
** disease
** treatment

.Task
For this exercise the requests are:

. Create database of patients and call it `patients`
. Insert 3 patient records with at least 1 history entry per patient
. Update patient data of 1 patient with new age, name and history entry
. Find all patients who are older than 30 (or a value of your choice)
. Delete all patients who got a cold as a disease

.Solution
The first thing to do is to set up the mongodb server using the terminal and run this command:

[source,bash]
----
sudo mongod
----

Then open another terminal and run the mongo client with:

[source,bash]
----
mongo
----

IMPORTANT: The mongo client don't need the root permission to write into the database

Let's create the database of patients:

[source,mongo]
----
use patients
----

Output:
[source,mongo]
----
switched to db patients
----

NOTE: This solve the first request

Now we can populate the DB with 3 patient:

[source,mongo]
----
db.patient.insertMany([
	{
		"firstName": "Gabriele",
		"lastName": "Puliti",
		"age": 26,
		"history": [
			{
				"disease": "cold",
				"treatment": "001"
			},
			{
				"disease": "headache",
				"treatment": "023"
			}
		]
	},
	{
		"firstName": "Dario",
		"lastName": "Scida",
		"age": 29,
		"history": [
			{
				"disease": "stomachache",
				"treatment": "025"
			}
		]
	},
	{
		"firstName": "Andrea",
		"lastName": "Amico",
		"age": 29,
		"history": [
			{
				"disease": "malignant herpes",
				"treatment": "250"
			}
		]
	}
])
----

Output:
[source,json]
----
{
	"acknowledged" : true,
	"insertedIds" : [
		ObjectId("5d1330a5aa6a78bdbaf6df77"),
		ObjectId("5d1330a5aa6a78bdbaf6df78"),
		ObjectId("5d1330a5aa6a78bdbaf6df79")
	]
}
----

NOTE: This solve the second request

One of the patients is set wrong in the DB, we need to change it using update:

[source, mongo]
----
db.patient.updateOne(
	{"_id" : ObjectId("5d1330a5aa6a78bdbaf6df79")},
	{$set:
		{
			"firstName":"Andrew",
			"lastName":"Friend",
			"age": 58,
			"history": [
				{
					"disease": "cough",
					"treatment": "003"
				},
				{
					"disease": "cold",
					"treatment": "001"
				}
			]
		}
	}
)
----

Output:
[source, json]
----
{ "acknowledged" : true, "matchedCount" : 1, "modifiedCount" : 1 }
----

NOTE: This solve the third request

To find all the patient that are older than 30 we need to use the find with the grater than condition:

[source,mongo]
----
db.patient.find({"age":{$gt:30}}).pretty()
----

Output:
[source,json]
----
{
	"_id" : ObjectId("5d1330a5aa6a78bdbaf6df79"),
	"firstName" : "Andrew",
	"lastName" : "Friend",
	"age" : 58,
	"history" : [
		{
			"disease" : "cough",
			"treatment" : "003"
		},
		{
			"disease" : "cold",
			"treatment" : "001"
		}
	]
}
----

NOTE: This solve the fourth request

The patients with cold can be discharged, it's necessary to remove from DB:

[source,mongo]
----
db.patient.deleteMany({"history.disease":"cold"})
----

Output:
[source,json]
----
{ "acknowledged" : true, "deletedCount" : 2 }
----

NOTE: This solve the last request


